In [26]:
import numpy as np
import time 

In [3]:
#execution_performance
size=10
py_list=list(range(size))
start=time.time()
sq_lsit=[x**2 for x in py_list]
end=time.time()
print(f"python list time ={end-start}  seconds")

np_arr=np.array(py_list)
start=time.time()
sq_array=np_arr ** 2
end=time.time()
print(f"numpy array time ={end-start}  seconds")


python list time =0.0001862049102783203  seconds
numpy array time =9.894371032714844e-05  seconds


In [4]:
#memory
import sys
print(sys.getsizeof(py_list))
# for x in py_list:
#     print(sys.getsizeof(x))

136


In [7]:
#  create  form  list
arr=np.array([1,2,3,4,5,"Mursalin"])
print(arr,type(arr),arr.dtype,arr.shape)
arr2D=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)


['1' '2' '3' '4' '5' 'Mursalin'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] <class 'numpy.ndarray'> int64 (3, 5)


In [20]:
#create
arr1=np.zeros((2,3),dtype="int64")
print(arr1)
arr2=np.ones((2,3),dtype="int64")
print(arr2)

arr3=np.eye((3),dtype="int64")
print(arr3)
arr4=np.full((3,4),100)
print(arr4)

arr5=np.arange(0,10,2)  #  start 0  and  print  0 2 4 .....8  
arr6=np.arange(1,10,2)  #  start 0  and  print  1 3 5 .....9
print(arr5)
print(arr6)
arr6=np.linspace(1,100,3)#evenly_space_arrays
print(arr6)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[0 2 4 6 8]
[1 3 5 7 9]
[  1.   50.5 100. ]


In [24]:
arr=np.array([[1,2,3],[3,4,5],[1,2,3]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)#  change  data_type
print(float_arr.dtype)

(3, 3)
9
int64
2
float64


In [28]:
#  important  operation  on  numpy_arrays
arr=np.array([[1,2,3],[4,5,6]])
reshaped=arr.reshape((3,2))
print(reshaped)
flattened=arr.flatten()  # 2d to  1d   array
print(flattened)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [38]:
#indexing an  array
arr=np.array([[1,2,3],[4,5,6]])
print(arr[:,0].sum())

5


In [43]:
#fancy _indexing
arr=np.array([1,2,3,4,5]);
idx=[1,3,4]
print(arr[idx])
print(arr[arr%2==1])

[2 4 5]
[1 3 5]


In [44]:
#slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [50]:
#copy vs  view
# nums=([1,2,3,4,5])  #  list  section
# sub_list=nums[1:3]
# print(sub_list)
# sub_list[0]=100
# print(sub_list)
# print(nums)

arr1=np.array([1,2,3,4,5])  #  list  section
sub_arr1=arr1[1:3].copy()
print(sub_arr1)
sub_arr1[0]=100
print(sub_arr1)
print(arr1)



[2 3]
[100   3]
[1 2 3 4 5]


In [52]:
#data_types
arr1=np.array([4+3j])
arr2=np.array([4+3j])
print(arr1+arr2)

[8.+6.j]


In [65]:
arr=np.array([[
  [1,2,3],
  [4,5,6]
],          
 [ [1,2,3],
  [4,5,6]
]])
print(np.sum(arr,axis=0))

[[ 2  4  6]
 [ 8 10 12]]


In [72]:
#row   wise  sum
arr=np.array([
  [1,2,3],
  [4,5,6]
]         
 )
print(np.sum(arr,axis=0))

#olumn   wise  sum
arr=np.array([
  [1,2,3],
  [4,5,6]
]         
 )
print(np.sum(arr,axis=1))




[5 7 9]
[ 6 15]


In [84]:
#3d  arrays

arr=np.array([[
  [1,2,3],
  [4,5,6]
],[
  [1,2,3],
  [4,5,6]
]
]       
 )
print(np.sum(arr,axis=0))  #  like   simple   matrix  sum   
print(np.sum(arr,axis=1))  # individual  matrix row sum 
print(np.sum(arr,axis=2))  # individual  matrix column sum 
print(arr[0,8:10,1:3])
arr[:,0,:]=99  #  first  row  of  both layers  and  replace



[[ 2  4  6]
 [ 8 10 12]]
[[5 7 9]
 [5 7 9]]
[[ 6 15]
 [ 6 15]]
[]


In [87]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,6],[8,9]])
print(arr1+arr2)

[[ 5  8]
 [11 13]]


In [89]:
#normalize
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std=np.std(arr)
normalize_arr=(arr-mean)/std
print(normalize_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [ ]:
#mathmatic_function

arr=np.array([1,2,4,5,7])
print(np.min(arr))
print(np.max(arr))
print(np.armin(arr)) # return  index
print(np.armax(arr))   # return  index
print(np.std(arr))   # return  index
print(np.mean(arr))   # return  index
print(np.median(arr))   # return  index
print(np.var(arr))   # return  index
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))
print(np.log10(arr))
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))  # only  integer  part  return
print(np.unique(arr)) 
print(np.sort(arr))  
print(np.sort(arr)) 
print(np.abs(arr)) 

